config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :menus
  resources :customers
  resources :order_details
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/set_current_customer', to: 'customers#set_current_customer'

  get '/reports', to: 'reports#index'
  get '/todays_report', to: 'reports#todays_report'
  post '/report_by_date_range', to: 'reports#report_by_date_range'
  post '/report_by_customer', to: 'reports#report_by_customer'
  post '/report_by_greater_than', to: 'reports#report_by_greater_than'
  post '/report_by_lower_than', to: 'reports#report_by_lower_than'

  # Defines the root path route ("/")
  root "customers#home"
  # root "articles#index"
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :category
  has_many :order_details
  has_many :orders, through: :order_details
  validates :price, comparison: { greater_than_or_equal_to: 0.01 }
  validates :description, length: {maximum: 150}
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: %i[ show edit update destroy ]

  def index
    @menus = Menu.all
  end

  def show
  end

  def new
    @menu = Menu.new
  end

  def edit
    @menu.category_id
  end

  def create
    @menu = Menu.new(menu_params)

    if @menu.save
      redirect_to menu_url(@menu), notice: "Menu was successfully created." 
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @menu.update(menu_params)
      redirect_to menu_url(@menu), notice: "Menu was successfully updated." 
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @menu.destroy
    redirect_to menus_url, notice: "Menu was successfully destroyed."
  end

  private
    def set_menu
      @menu = Menu.find(params[:id])
    end

    def menu_params
      params.require(:menu).permit(:name, :price, :description, :category_id)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= form_with(model: menu) do |form| %>
  <% if menu.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
        <% menu.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%=   select(:menu, :category_id, Category.all.collect { |c| [ c.name, c.id ] }, { include_blank: "Select Category" }) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/menus/_menu.html.erb
<div id="<%= dom_id menu %>">
  <p>
    <strong>Name:</strong>
    <%= menu.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= menu.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= menu.description %>
  </p>

</div>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render "form", menu: @menu %>

<br>

<div>
  <%= link_to "Show this menu", @menu %> |
  <%= link_to "Back to menus", menus_path %>
</div>

app/views/menus/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Menus</h1>

<div id="menus">
  <% @menus.each do |menu| %>
    <%= render menu %>
    <p>
      <%= link_to "Show this menu", menu %>
    </p>
  <% end %>
</div>

<p><%= link_to "New menu", new_menu_path %></p>
<p><%= link_to "Order here", orders_path %></p>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render "form", menu: @menu %>

<br>

<div>
  <%= link_to "Back to menus", menus_path %>
</div>

app/views/menus/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @menu %>

<div>
  <%= link_to "Edit this menu", edit_menu_path(@menu) %> |
  <%= link_to "Back to menus", menus_path %>

  <%= button_to "Destroy this menu", @menu, method: :delete %>
</div>