config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :menus
  resources :customers
  resources :order_details
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/set_current_customer', to: 'customers#set_current_customer'

  get '/reports', to: 'reports#index'
  get '/todays_report', to: 'reports#todays_report'
  post '/report_by_date_range', to: 'reports#report_by_date_range'
  post '/report_by_customer', to: 'reports#report_by_customer'
  post '/report_by_greater_than', to: 'reports#report_by_greater_than'
  post '/report_by_lower_than', to: 'reports#report_by_lower_than'

  # Defines the root path route ("/")
  root "customers#home"
  # root "articles#index"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :menus, through: :order_details
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  def index
    if session[:current_customer].present?
      @orders = Order.where("customer_id = ?", session[:current_customer]["id"])
    else
      redirect_to root_path
    end
  end

  def show
    session[:current_order] = @order.id
    @order_details = OrderDetail.where("order_id = ?", params[:id])
  end

  def new
    if session[:current_customer].present?
      @order = Order.new
    else
      redirect_to root_path
    end
  end

  def edit

  end

  def create
    @order = Order.new(order_params.merge(customer_id: session[:current_customer]["id"]))

    if @order.save
      redirect_to order_url(@order), notice: "Order was successfully created." 
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def update
    if @order.update(order_params)
      redirect_to order_url(@order), notice: "Order was successfully updated." 
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @order.destroy
    destroy_order_details(@order.id)

    redirect_to orders_url, notice: "Order was successfully destroyed." 
   
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.permit(:total_price, :status)
    end
    
    def destroy_order_details(id)
      order_details = OrderDetail.where("order_id = ?", id)
      order_details.each do |order_detail|
        order_detail.destroy
      end
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <label for="status">Status: </label>
  <select name="status" id="status">
    <option value="NEW">New</option>
    <option value="PAID">Paid</option>
    <option value="CANCELED">Canceled</option>
  </select>
  <br><br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Customer:</strong>
    <%= order.customer.email %>
  </p>

  <p>
    <strong>Total price:</strong>
    <%= order.total_price %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= order.status %>
  </p>

</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "My Orders", orders_path %>
  <p><%= link_to "Back", :back %></p>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <table style="margin-bottom: 16px;">
    <tr>
      <th style="padding: 4px 12px;">Customer</th>
      <th style="padding: 4px 12px;">Total Price</th>
      <th style="padding: 4px 12px;">Status</th>
      <th></th>
    </tr>
    <% @orders.each do |order| %>
      <tr>
        <td style="padding: 4px 12px;"><%=order.customer.email %></td>
        <td style="padding: 4px 12px;"><%=order.total_price %></td>
        <td style="padding: 4px 12px;"><%=order.status %></td>
        <td style="padding: 4px 12px;"><%= link_to "Show this order", order %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<form method="post" action="/orders">
  <input type="hidden" id="total_price" name="total_price" value=0.0> 
  <input type="hidden" id="status" name="status" value="NEW">
  <input type="submit" value="Create Order">
</form>

<br>

<div>
  <%= link_to "My Orders", orders_path %>
  <p><%= link_to "Back", :back %></p>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>
<h3>Menu ordered : </h3>
<div id="order_details">
  <table>
    <tr>
      <th style="padding: 4px 12px;">Name</th>
      <th style="padding: 4px 12px;">Quantity</th>
      <th style="padding: 4px 12px;">Sum Price</th>
      <th></th>
    </tr>
    <% @order_details.each do |order_detail| %>
      <tr>
        <td style="padding: 4px 12px;"><%=order_detail.menu.name %></td>
        <td style="padding: 4px 12px;"><%=order_detail.quantity %></td>
        <td style="padding: 4px 12px;"><%=order_detail.sum_price %></td>
      </tr>
    <% end %>
  </table>
</div>

<div>
  <p><%= link_to "Edit order cart", order_details_url %></p>
  <p><%= link_to "Edit status order", edit_order_path(@order) %></p>
  <p><%= link_to "My Orders", orders_path %></p>
  <p><%= link_to "Back", :back %></p>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>