config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :menus
  resources :customers
  resources :order_details
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/set_current_customer', to: 'customers#set_current_customer'

  get '/reports', to: 'reports#index'
  get '/todays_report', to: 'reports#todays_report'
  post '/report_by_date_range', to: 'reports#report_by_date_range'
  post '/report_by_customer', to: 'reports#report_by_customer'
  post '/report_by_greater_than', to: 'reports#report_by_greater_than'
  post '/report_by_lower_than', to: 'reports#report_by_lower_than'

  # Defines the root path route ("/")
  root "customers#home"
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Family Catering</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= link_to "Home", '/' %>
    <%= link_to "Customers", customers_path %>
    <%= link_to "Menus", menus_path %>
    <%= link_to "Categories", categories_path %>
    <%= link_to "Orders", orders_path %>
    <%= link_to "Reports", reports_path %>
    <% if session[:current_customer].present? %>
      <p>Logged in as <strong><%=session[:current_customer]["email"]%></strong></p>
    <% end %>
    <%= yield %>
  </body>
</html>